# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.5
_src_path: https://github.com/stellarshenson/copier-data-science.git
author_name: Andrew Jelen
custom_config: ''
dataset_storage: s3
dependency_file: pyproject.toml
description: Project to simulate number of different events
docker_support: 'No'
docs: none
env_encryption: 'Yes'
env_name: henryk-sim
environment_manager: uv
git_init: 'Yes'
jupyter_kernel_support: 'Yes'
linting_and_formatting: ruff
module_name: henryk_simulations
open_source_license: MIT
package_repository: 'No'
pydata_packages: none
python_version_number: '3.12'
repo_name: henryk-simulations
s3_aws_profile: stellars-tech
s3_bucket: ''
testing_framework: pytest
