"""Corridor two-body kinematic plausibility simulation.

Models a contested sequence of two-body movements in a 2 m corridor over 3 s:
pull, position-swap, throw, simultaneous neck-reach, 180 deg re-orientation.

Submodules:
    config         scenario, geometry, bodies, phase dataclasses with defaults
    kinematics     per-phase analytical computation (v, a, F, impulse, energy)
    acoustics      plate modes, cavity coupling, SPL prediction for door impact
    references     biomechanical reference distributions (scipy.stats)
    plausibility   z-score and verdict against references
    sim            PyBullet driver, two humanoid URDFs, MP4 export
    plots          matplotlib figures (timeline, forces, distribution overlays)
"""

from henryk_simulations.corridor.acoustics import (
    DEFAULT_ELEVATOR_DOOR,
    DEFAULT_ETA_RANGE,
    DEFAULT_LISTENERS,
    REF_SOUNDS,
    AcousticPrediction,
    AcousticSource,
    DoorGeometry,
    MaterialProps,
    PlateMode,
    PlatePanel,
    cavity_axial_frequency,
    frequency_band,
    plate_modes,
    predict_signature,
    spl_at_distance,
)
from henryk_simulations.corridor.audiomix import (
    AudioMixConfig,
    AudioMixResult,
    align_peak,
    augment_event,
    decode_audio,
    encode_m4a,
    load_synth_sound,
    mix_event,
)
from henryk_simulations.corridor.bodyfem import (
    BodyFEMConfig,
    BodyFEMResult,
    TorsoFEM,
    TorsoMesh,
    air_escape,
    assemble_fem,
    boundary_facets,
    deceleration_pulse,
    decimate_mesh,
    ensure_body_mesh,
    impact_response,
    isolate_upper_torso,
    load_body_mesh,
    peak_spl,
    radiate_modes,
    solve_body_fem,
    solve_modes,
    sound_levels,
    tet_mesh_volume,
    voxelise_torso,
    write_listening_wav,
)
from henryk_simulations.corridor.choreography import (
    ChoreographyConfig,
    ChoreographyResult,
    Constraint,
    FreeParameter,
    ImpactSingularity,
    PhaseTrajectory,
    constraints,
    free_parameters,
    impact_singularity,
    solve_choreography,
    solve_envelope,
)
from henryk_simulations.corridor.config import (
    DEFAULT_PHASE_DURATIONS,
    Bodies,
    Geometry,
    Phase,
    Scenario,
    default_scenario,
)
from henryk_simulations.corridor.impact import (
    BodySegment,
    ContactPatch,
    EffectiveMass,
    FractureThreshold,
    FractureVerdict,
    ImpactConfig,
    ImpactDynamicsResult,
    assess_fracture,
    body_segments,
    contact_area,
    effective_impact_mass,
    fracture_thresholds,
    ribs_engaged,
    solve_impact,
    solve_impact_envelope,
)
from henryk_simulations.corridor.injuries import (
    INJURY_TABLE,
    REFERENCE_AGE,
    TISSUE_CLASSES,
    InjuryPrediction,
    InjuryThreshold,
    injury_table,
    predict_injuries,
    tolerance_factor,
)
from henryk_simulations.corridor.kinematics import (
    ImpactResult,
    PhaseResult,
    compute_impact,
    compute_phase_kinematics,
    compute_scenario,
)
from henryk_simulations.corridor.plausibility import (
    PlausibilityScore,
    Verdict,
    score_phase,
)
from henryk_simulations.corridor.references import (
    Reference,
    ReferenceLibrary,
    default_library,
)
from henryk_simulations.corridor.reverb import (
    CorridorImpulseResponse,
    CorridorReverbConfig,
    apply_corridor_reverb,
    corridor_impulse_response,
)

__all__ = [
    "DEFAULT_ELEVATOR_DOOR",
    "DEFAULT_ETA_RANGE",
    "DEFAULT_LISTENERS",
    "DEFAULT_PHASE_DURATIONS",
    "INJURY_TABLE",
    "REFERENCE_AGE",
    "REF_SOUNDS",
    "TISSUE_CLASSES",
    "AcousticPrediction",
    "AcousticSource",
    "AudioMixConfig",
    "AudioMixResult",
    "Bodies",
    "BodyFEMConfig",
    "BodyFEMResult",
    "BodySegment",
    "ChoreographyConfig",
    "ChoreographyResult",
    "Constraint",
    "ContactPatch",
    "CorridorImpulseResponse",
    "CorridorReverbConfig",
    "DoorGeometry",
    "EffectiveMass",
    "FractureThreshold",
    "FractureVerdict",
    "FreeParameter",
    "Geometry",
    "ImpactConfig",
    "ImpactDynamicsResult",
    "ImpactResult",
    "ImpactSingularity",
    "InjuryPrediction",
    "InjuryThreshold",
    "MaterialProps",
    "Phase",
    "PhaseResult",
    "PhaseTrajectory",
    "PlateMode",
    "PlatePanel",
    "PlausibilityScore",
    "Reference",
    "ReferenceLibrary",
    "Scenario",
    "TorsoFEM",
    "TorsoMesh",
    "Verdict",
    "air_escape",
    "align_peak",
    "apply_corridor_reverb",
    "assemble_fem",
    "assess_fracture",
    "augment_event",
    "body_segments",
    "boundary_facets",
    "cavity_axial_frequency",
    "compute_impact",
    "compute_phase_kinematics",
    "compute_scenario",
    "constraints",
    "contact_area",
    "corridor_impulse_response",
    "deceleration_pulse",
    "decimate_mesh",
    "decode_audio",
    "default_library",
    "default_scenario",
    "effective_impact_mass",
    "encode_m4a",
    "ensure_body_mesh",
    "fracture_thresholds",
    "free_parameters",
    "frequency_band",
    "impact_response",
    "impact_singularity",
    "injury_table",
    "isolate_upper_torso",
    "load_body_mesh",
    "load_synth_sound",
    "mix_event",
    "peak_spl",
    "plate_modes",
    "predict_injuries",
    "predict_signature",
    "radiate_modes",
    "ribs_engaged",
    "score_phase",
    "solve_body_fem",
    "solve_choreography",
    "solve_envelope",
    "solve_impact",
    "solve_impact_envelope",
    "solve_modes",
    "sound_levels",
    "spl_at_distance",
    "tet_mesh_volume",
    "tolerance_factor",
    "voxelise_torso",
    "write_listening_wav",
]
